version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: portainer-ce_server_1
      APP_PORT: 9000
    
  server:
    image: portainer/portainer-ce:latest
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
